name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: apt install -y cmake cppcheck
    - name: cppcheck
      run: cppcheck --enable=warning,style,performance,portability,information,missingInclude converters/
    - name: Configure
      run: |
        cd converters
        cmake .
    - name: Build
      run: |
        cd converters
        make
