name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: sudo apt install -y cmake cppcheck libopencascade-dev unzip wget
    - name: Install Sonar
      run: |
        wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
        unzip build-wrapper-linux-x86.zip
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
        unzip sonar-scanner-cli-4.2.0.1873-linux.zip
    - name: cppcheck
      run: cppcheck --enable=warning,style,performance,portability,information,missingInclude converters/
    - name: Configure
      run: |
        cd converters
        cmake .
    - name: Build
      run: |
        cd converters
        make
