name: C/C++ CI SonarCloud

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          sudo apt update
          sudo apt install -y cppcheck
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
          unzip sonar-scanner-cli-4.2.0.1873-linux.zip
      - name: sonar
        env:
          SONAR_LOGIN: ${{ secrets.SONARCLOUD_LOGIN }}
        run: |
          cd converters
          build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output make clean all
          sonar-scanner \
            -Dsonar.organization=airthium \
            -Dsonar.projectKey=Airthium_tanatloc-dockers \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.cfamily.build-wrapper-output=bw-output \
            -Dsonar.login=${SONAR_LOGIN}
